package hap.exam.hscs_itf_mapping_values.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "hscs_itf_mapping_values")
public class ItfMappingValues extends BaseDTO {

     public static final String FIELD_VALUE_ID = "valueId";
     public static final String FIELD_HEADER_ID = "headerId";
     public static final String FIELD_VALUE1 = "value1";
     public static final String FIELD_VALUE2 = "value2";
     public static final String FIELD_VALUE3 = "value3";
     public static final String FIELD_VALUE4 = "value4";
     public static final String FIELD_VALUE5 = "value5";
     public static final String FIELD_VALUE6 = "value6";
     public static final String FIELD_VALUE7 = "value7";
     public static final String FIELD_VALUE8 = "value8";
     public static final String FIELD_VALUE9 = "value9";
     public static final String FIELD_VALUE10 = "value10";
     public static final String FIELD_VALUE11 = "value11";
     public static final String FIELD_VALUE12 = "value12";
     public static final String FIELD_VALUE13 = "value13";
     public static final String FIELD_VALUE14 = "value14";
     public static final String FIELD_VALUE15 = "value15";
     public static final String FIELD_VALUE16 = "value16";
     public static final String FIELD_VALUE17 = "value17";
     public static final String FIELD_VALUE18 = "value18";
     public static final String FIELD_VALUE19 = "value19";
     public static final String FIELD_VALUE20 = "value20";
     public static final String FIELD_PROGRAM_ID = "programId";
     public static final String FIELD_REQUEST_ID = "requestId";


     @Id
     @GeneratedValue
     private Long valueId;

     @NotNull
     private Long headerId;

     @Length(max = 240)
     private String value1;

     @Length(max = 240)
     private String value2;

     @Length(max = 240)
     private String value3;

     @Length(max = 240)
     private String value4;

     @Length(max = 240)
     private String value5;

     @Length(max = 240)
     private String value6;

     @Length(max = 240)
     private String value7;

     @Length(max = 240)
     private String value8;

     @Length(max = 240)
     private String value9;

     @Length(max = 240)
     private String value10;

     @Length(max = 240)
     private String value11;

     @Length(max = 240)
     private String value12;

     @Length(max = 240)
     private String value13;

     @Length(max = 240)
     private String value14;

     @Length(max = 240)
     private String value15;

     @Length(max = 240)
     private String value16;

     @Length(max = 240)
     private String value17;

     @Length(max = 240)
     private String value18;

     @Length(max = 240)
     private String value19;

     @Length(max = 240)
     private String value20;

     private Long programId;

     private Long requestId;


     public void setValueId(Long valueId){
         this.valueId = valueId;
     }

     public Long getValueId(){
         return valueId;
     }

     public void setHeaderId(Long headerId){
         this.headerId = headerId;
     }

     public Long getHeaderId(){
         return headerId;
     }

     public void setValue1(String value1){
         this.value1 = value1;
     }

     public String getValue1(){
         return value1;
     }

     public void setValue2(String value2){
         this.value2 = value2;
     }

     public String getValue2(){
         return value2;
     }

     public void setValue3(String value3){
         this.value3 = value3;
     }

     public String getValue3(){
         return value3;
     }

     public void setValue4(String value4){
         this.value4 = value4;
     }

     public String getValue4(){
         return value4;
     }

     public void setValue5(String value5){
         this.value5 = value5;
     }

     public String getValue5(){
         return value5;
     }

     public void setValue6(String value6){
         this.value6 = value6;
     }

     public String getValue6(){
         return value6;
     }

     public void setValue7(String value7){
         this.value7 = value7;
     }

     public String getValue7(){
         return value7;
     }

     public void setValue8(String value8){
         this.value8 = value8;
     }

     public String getValue8(){
         return value8;
     }

     public void setValue9(String value9){
         this.value9 = value9;
     }

     public String getValue9(){
         return value9;
     }

     public void setValue10(String value10){
         this.value10 = value10;
     }

     public String getValue10(){
         return value10;
     }

     public void setValue11(String value11){
         this.value11 = value11;
     }

     public String getValue11(){
         return value11;
     }

     public void setValue12(String value12){
         this.value12 = value12;
     }

     public String getValue12(){
         return value12;
     }

     public void setValue13(String value13){
         this.value13 = value13;
     }

     public String getValue13(){
         return value13;
     }

     public void setValue14(String value14){
         this.value14 = value14;
     }

     public String getValue14(){
         return value14;
     }

     public void setValue15(String value15){
         this.value15 = value15;
     }

     public String getValue15(){
         return value15;
     }

     public void setValue16(String value16){
         this.value16 = value16;
     }

     public String getValue16(){
         return value16;
     }

     public void setValue17(String value17){
         this.value17 = value17;
     }

     public String getValue17(){
         return value17;
     }

     public void setValue18(String value18){
         this.value18 = value18;
     }

     public String getValue18(){
         return value18;
     }

     public void setValue19(String value19){
         this.value19 = value19;
     }

     public String getValue19(){
         return value19;
     }

     public void setValue20(String value20){
         this.value20 = value20;
     }

     public String getValue20(){
         return value20;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
