package hap.exam.hscs_itf_imp_lines.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "hscs_itf_imp_lines")
public class ItfImpLines extends BaseDTO {

     public static final String FIELD_LINE_ID = "lineId";
     public static final String FIELD_HEADER_ID = "headerId";
     public static final String FIELD_SOURCE_ITERFACE_ID = "sourceIterfaceId";
     public static final String FIELD_PROCESS_DATE = "processDate";
     public static final String FIELD_IMPORT_STATUS = "importStatus";
     public static final String FIELD_PROCESS_STATUS = "processStatus";
     public static final String FIELD_PROCESS_GROUP = "processGroup";
     public static final String FIELD_STATEMENT_STATUS = "statementStatus";
     public static final String FIELD_STATEMENT_DATE = "statementDate";
     public static final String FIELD_PROCESS_MESSAGE = "processMessage";
     public static final String FIELD_PROGRAM_ID = "programId";
     public static final String FIELD_REQUEST_ID = "requestId";


     @Id
     @GeneratedValue
     private Long lineId; //表ID，主键，供其他表做外键

     @NotNull
     private Long headerId; //头表ID，用于关联本行数据所属的批次

     @NotNull
     private Long sourceIterfaceId; //来源ID，INTERFACE表主键ID

     private Date processDate; //后台处理日期，比如生成结算单日期

     @NotEmpty
     @Length(max = 1)
     private String importStatus; //业务单据生成状态，N/S/E/P

     @Length(max = 1)
     private String processStatus; //导入数据至行表拆分校验状态，N/S/E/P

     private Long processGroup; //生成结算单数据批次

     @Length(max = 30)
     private String statementStatus; //对账状态

     private Date statementDate; //对账日期

     @Length(max = 4000)
     private String processMessage; //后台处理信息

     private Long programId;

     private Long requestId;


     public void setLineId(Long lineId){
         this.lineId = lineId;
     }

     public Long getLineId(){
         return lineId;
     }

     public void setHeaderId(Long headerId){
         this.headerId = headerId;
     }

     public Long getHeaderId(){
         return headerId;
     }

     public void setSourceIterfaceId(Long sourceIterfaceId){
         this.sourceIterfaceId = sourceIterfaceId;
     }

     public Long getSourceIterfaceId(){
         return sourceIterfaceId;
     }

     public void setProcessDate(Date processDate){
         this.processDate = processDate;
     }

     public Date getProcessDate(){
         return processDate;
     }

     public void setImportStatus(String importStatus){
         this.importStatus = importStatus;
     }

     public String getImportStatus(){
         return importStatus;
     }

     public void setProcessStatus(String processStatus){
         this.processStatus = processStatus;
     }

     public String getProcessStatus(){
         return processStatus;
     }

     public void setProcessGroup(Long processGroup){
         this.processGroup = processGroup;
     }

     public Long getProcessGroup(){
         return processGroup;
     }

     public void setStatementStatus(String statementStatus){
         this.statementStatus = statementStatus;
     }

     public String getStatementStatus(){
         return statementStatus;
     }

     public void setStatementDate(Date statementDate){
         this.statementDate = statementDate;
     }

     public Date getStatementDate(){
         return statementDate;
     }

     public void setProcessMessage(String processMessage){
         this.processMessage = processMessage;
     }

     public String getProcessMessage(){
         return processMessage;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
