package hap.exam.itf_defination_lines.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@ExtensionAttribute(disable = true)
@Table(name = "hscs_itf_defination_lines")
public class ItfDefinationLines extends BaseDTO implements Comparable<ItfDefinationLines> {

    public static final String FIELD_LINE_ID = "lineId";
    public static final String FIELD_HEADER_ID = "headerId";
    public static final String FIELD_TITLE_TEXT = "titleText";
    public static final String FIELD_COLUMN_TYPE = "columnType";
    public static final String FIELD_COLUMN_NAME = "columnName";
    public static final String FIELD_SEQ_NUM = "seqNum";
    public static final String FIELD_VALUE_TYPE = "valueType";
    public static final String FIELD_COLUMN_LEN = "columnLen";
    public static final String FIELD_VALUE_SET = "valueSet";
    public static final String FIELD_COLUMN_FORMAT = "columnFormat";
    public static final String FIELD_REQUIRED_FLAG = "requiredFlag";
    public static final String FIELD_SHOW_FLAG = "showFlag";
    public static final String FIELD_ENABLE_FLAG = "enableFlag";
    public static final String FIELD_UNIQUE_FLAG = "uniqueFlag";
    public static final String FIELD_SHOW_LENGTH = "showLength";
    public static final String FIELD_PROGRAM_ID = "programId";
    public static final String FIELD_REQUEST_ID = "requestId";


    @Id
    @GeneratedValue
    private Long lineId; //表ID，主键，供其他表做外键

    @NotNull
    private Long headerId; //头ID

    @NotEmpty
    @Length(max = 60)
    private String titleText; //标题

    @NotEmpty
    @Length(max = 30)
    private String columnType; //字段类型，code关键字

    @NotEmpty
    @Length(max = 100)
    private String columnName; //列名

    @NotNull
    private Long seqNum; //序号

    @NotEmpty
    @Length(max = 30)
    private String valueType; //值类型，code关键字

    private Long columnLen; //字段长度

    @Length(max = 60)
    private String valueSet; //验证值集
    @Length(max = 150)
    private String flexSetColumn;//值集校验列

    @Length(max = 100)
    private String columnFormat; //验证格式

    @NotEmpty
    @Length(max = 1)
    private String requiredFlag; //必输，即如果未给值就报错

    @NotEmpty
    @Length(max = 1)
    private String showFlag; //显示

    @NotEmpty
    @Length(max = 1)
    private String enableFlag; //是否启用，不启用则此字段不会用于模板校验和给值

    @NotEmpty
    @Length(max = 1)
    private String uniqueFlag; //是否唯一，唯一则需整体验证字段值无重复

    private Long showLength; //字段显示长度

    private Long programId;

    private Long requestId;


    public void setLineId(Long lineId) {
        this.lineId = lineId;
    }

    public Long getLineId() {
        return lineId;
    }

    public void setHeaderId(Long headerId) {
        this.headerId = headerId;
    }

    public Long getHeaderId() {
        return headerId;
    }

    public void setTitleText(String titleText) {
        this.titleText = titleText;
    }

    public String getTitleText() {
        return titleText;
    }

    public void setColumnType(String columnType) {
        this.columnType = columnType;
    }

    public String getColumnType() {
        return columnType;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    public String getColumnName() {
        return columnName;
    }

    public void setSeqNum(Long seqNum) {
        this.seqNum = seqNum;
    }

    public Long getSeqNum() {
        return seqNum;
    }

    public void setValueType(String valueType) {
        this.valueType = valueType;
    }

    public String getValueType() {
        return valueType;
    }

    public void setColumnLen(Long columnLen) {
        this.columnLen = columnLen;
    }

    public Long getColumnLen() {
        return columnLen;
    }

    public void setValueSet(String valueSet) {
        this.valueSet = valueSet;
    }

    public String getValueSet() {
        return valueSet;
    }

    public void setColumnFormat(String columnFormat) {
        this.columnFormat = columnFormat;
    }

    public String getColumnFormat() {
        return columnFormat;
    }

    public void setRequiredFlag(String requiredFlag) {
        this.requiredFlag = requiredFlag;
    }

    public String getRequiredFlag() {
        return requiredFlag;
    }

    public void setShowFlag(String showFlag) {
        this.showFlag = showFlag;
    }

    public String getShowFlag() {
        return showFlag;
    }

    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }

    public String getEnableFlag() {
        return enableFlag;
    }

    public void setUniqueFlag(String uniqueFlag) {
        this.uniqueFlag = uniqueFlag;
    }

    public String getUniqueFlag() {
        return uniqueFlag;
    }

    public void setShowLength(Long showLength) {
        this.showLength = showLength;
    }

    public Long getShowLength() {
        return showLength;
    }

    public void setProgramId(Long programId) {
        this.programId = programId;
    }

    public Long getProgramId() {
        return programId;
    }

    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }

    public Long getRequestId() {
        return requestId;
    }

    @Override
    public int compareTo(ItfDefinationLines o) {
        Long num = this.getSeqNum()-o.getSeqNum();
        return num.intValue();
    }
}
