package hap.exam.hscs_itf_mapping_lines.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "hscs_itf_mapping_lines")
public class ItfMappingLines extends BaseDTO {

     public static final String FIELD_LINE_ID = "lineId";
     public static final String FIELD_HEADER_ID = "headerId";
     public static final String FIELD_LINE_NUM = "lineNum";
     public static final String FIELD_FIELD_TYPE = "fieldType";
     public static final String FIELD_ITF_LINE_ID = "itfLineId";
     public static final String FIELD_TITLE_TEXT = "titleText";
     public static final String FIELD_PROGRAM_ID = "programId";
     public static final String FIELD_REQUEST_ID = "requestId";


     @Id
     @GeneratedValue
     private Long lineId; //表ID，主键，供其他表做外键

     @NotNull
     private Long headerId; //映射头ID

     @NotNull
     private Long lineNum; //行号

     @NotEmpty
     @Length(max = 30)
     private String fieldType; //字段类型，code关键字

     @NotNull
     private Long itfLineId; //接口定义行ID，关联获取字段名称

     @NotEmpty
     @Length(max = 240)
     private String titleText; //标题

     private Long programId;

     private Long requestId;


     public void setLineId(Long lineId){
         this.lineId = lineId;
     }

     public Long getLineId(){
         return lineId;
     }

     public void setHeaderId(Long headerId){
         this.headerId = headerId;
     }

     public Long getHeaderId(){
         return headerId;
     }

     public void setLineNum(Long lineNum){
         this.lineNum = lineNum;
     }

     public Long getLineNum(){
         return lineNum;
     }

     public void setFieldType(String fieldType){
         this.fieldType = fieldType;
     }

     public String getFieldType(){
         return fieldType;
     }

     public void setItfLineId(Long itfLineId){
         this.itfLineId = itfLineId;
     }

     public Long getItfLineId(){
         return itfLineId;
     }

     public void setTitleText(String titleText){
         this.titleText = titleText;
     }

     public String getTitleText(){
         return titleText;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
