package hap.exam.hscs_itf_mapping_headers.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "hscs_itf_mapping_headers")
public class ItfMappingHeaders extends BaseDTO {

     public static final String FIELD_HEADER_ID = "headerId";
     public static final String FIELD_MAPPING_NAME = "mappingName";
     public static final String FIELD_MODULE_CODE = "moduleCode";
     public static final String FIELD_ITF_HEADER_ID = "itfHeaderId";
     public static final String FIELD_FLEX_SET_NAME = "flexSetName";
     public static final String FIELD_START_ACTIVE_DATE = "startActiveDate";
     public static final String FIELD_END_ACTIVE_DATE = "endActiveDate";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_PROGRAM_ID = "programId";
     public static final String FIELD_REQUEST_ID = "requestId";


     @Id
     @GeneratedValue
     private Long headerId; //表ID，主键，供其他表做外键

     @NotEmpty
     @Length(max = 240)
     private String mappingName; //映射名称

     @NotEmpty
     @Length(max = 30)
     private String moduleCode; //所属模块，CR：结算，ITF：接口

     @NotNull
     private Long itfHeaderId; //接口名称

     @Length(max = 80)
     private String flexSetName; //值集名称

     private Date startActiveDate; //开始日期

     private Date endActiveDate; //截止日期

     @Length(max = 240)
     private String description; //映射说明

     private Long programId;

     private Long requestId;


     public void setHeaderId(Long headerId){
         this.headerId = headerId;
     }

     public Long getHeaderId(){
         return headerId;
     }

     public void setMappingName(String mappingName){
         this.mappingName = mappingName;
     }

     public String getMappingName(){
         return mappingName;
     }

     public void setModuleCode(String moduleCode){
         this.moduleCode = moduleCode;
     }

     public String getModuleCode(){
         return moduleCode;
     }

     public void setItfHeaderId(Long itfHeaderId){
         this.itfHeaderId = itfHeaderId;
     }

     public Long getItfHeaderId(){
         return itfHeaderId;
     }

     public void setFlexSetName(String flexSetName){
         this.flexSetName = flexSetName;
     }

     public String getFlexSetName(){
         return flexSetName;
     }

     public void setStartActiveDate(Date startActiveDate){
         this.startActiveDate = startActiveDate;
     }

     public Date getStartActiveDate(){
         return startActiveDate;
     }

     public void setEndActiveDate(Date endActiveDate){
         this.endActiveDate = endActiveDate;
     }

     public Date getEndActiveDate(){
         return endActiveDate;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
