package hap.exam.itf_defination.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "hscs_itf_defination_headers")
public class ItfDefinationHeaders extends BaseDTO {

    public static final String FIELD_HEADER_ID = "headerId";
    public static final String FIELD_INTERFACE_NAME = "interfaceName";
    public static final String FIELD_DESCRIPTION = "description";
    public static final String FIELD_MODULE_CODE = "moduleCode";
    public static final String FIELD_DATA_CLASS = "dataClass";
    public static final String FIELD_START_DATE = "startDate";
    public static final String FIELD_END_DATE = "endDate";
    public static final String FIELD_FROZEN_FLAG = "frozenFlag";
    public static final String FIELD_PROGRAM_ID = "programId";
    public static final String FIELD_REQUEST_ID = "requestId";


    @Id
    @GeneratedValue
    private Long headerId; //表ID，主键，供其他表做外键


    @NotEmpty
    @Length(max = 240)
    @Condition(operator="like")
    private String interfaceName; //接口名称

    @NotEmpty
    @Length(max = 240)
    @Condition(operator="like")
    private String description; //接口说明

    @NotEmpty
    @Length(max = 30)
    private String moduleCode; //所属模块，CR：结算，ITF：接口

    @NotEmpty
    @Length(max = 30)
    private String dataClass; //数据类型编码，同值集关联可取名称


    @DateTimeFormat(pattern = "yyyy/MM/dd HH:mm:ss")
    private Date startDate; //起始日期
    @Transient
    private String strStartDate;//起始日期的字符类型。


    @DateTimeFormat(pattern = "yyyy/MM/dd HH:mm:ss")
    private Date endDate; //截止日期
    @Transient
    private String strEndDate;//自定义的截止日期的字符类型。

    @Length(max = 1)
    private String frozenFlag; //冻结标记

    private Long programId;

    private Long requestId;
    //将字符类型转换为日期类型。
    public Date convertStrToDate(String str) throws ParseException {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy/MM/dd");
        return simpleDateFormat.parse(str);
    }

    public String getStrStartDate(){

        return strStartDate;
    }

    public String getStrEndDate() {
        return strEndDate;
    }

    public void setStrEndDate(String strEndDate) throws ParseException {
        this.strEndDate = strEndDate;
        if(strEndDate!=null&&!strEndDate.equals("")){
            this.endDate = convertStrToDate(strEndDate);
        }
    }

    public void setStrStartDate(String strStartDate) throws ParseException {
        this.strStartDate = strStartDate;
        //将strStartDate赋值给startDate
        if(strStartDate!=null&&!strStartDate.equals("")){}
        this.startDate =  convertStrToDate(strStartDate);
    }

    public void setHeaderId(Long headerId) {
        this.headerId = headerId;
    }

    public Long getHeaderId() {
        return headerId;
    }

    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }

    public String getInterfaceName() {
        return interfaceName;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setModuleCode(String moduleCode) {
        this.moduleCode = moduleCode;
    }

    public String getModuleCode() {
        return moduleCode;
    }

    public void setDataClass(String dataClass) {
        this.dataClass = dataClass;
    }

    public String getDataClass() {
        return dataClass;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setFrozenFlag(String frozenFlag) {
        this.frozenFlag = frozenFlag;
    }

    public String getFrozenFlag() {
        return frozenFlag;
    }

    public void setProgramId(Long programId) {
        this.programId = programId;
    }

    public Long getProgramId() {
        return programId;
    }

    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }

    public Long getRequestId() {
        return requestId;
    }

    @Override
    public String toString() {
        return "ItfDefinationHeaders{" +
                "headerId=" + headerId +
                ", interfaceName='" + interfaceName + '\'' +
                ", description='" + description + '\'' +
                ", moduleCode='" + moduleCode + '\'' +
                ", dataClass='" + dataClass + '\'' +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                ", frozenFlag='" + frozenFlag + '\'' +
                ", programId=" + programId +
                ", requestId=" + requestId +
                '}';
    }
}
